# Лабораторная работа №1
# Решение обыкновенных дифференциальных уравнений

## 1. Методы решения ОДУ

Существует большое количество методов численного решения задачи. Для решения ОДУ в данной лабораторной работе будут использованы: явный и неявный метод Эйлера, усовершенствованный метод Эйлера, методы Гира различных порядков (1-го, 2-го и 4-го).

При построении численных алгоритмов будем считать, что решение этой дифференциальной задачи существует, оно единственно и обладает необходимыми свойствами гладкости.

Идея численных методов решения задачи состоит из четырех частей:
1. Вводится расчетная сетка по переменной t (время) из $N_{t}+1$ точки $t_{0}, t_{1}, ..., t_{N_{t}}$. Нужно найти значения неизвестной функции **u** в узлах сетки $t_{n}$. Обозначим через $y^{n}$ приближенное значение **u**($t_{n}$).

2. Предполагаем, что дифференциальное уравнение выполнено в узлах сетки.

3. Аппроксимируем производные конечными разностями.

4. Формулируем алгоритм, который вычисляет новые значения $y^{n+1}$ на основе предыдущих вычисленных значений $y^{k}$, $k < n$

Метод сходится в точке $t_{n}$, если $\left | y^{n} - u(t_{n}) \right | \rightarrow 0$ при $\tau \rightarrow 0$. Метод имеет $p$-ый порядок точности, если $\left | y^{n} - u(t_{n}) \right | = O(\tau^{p}), p > 0$ при $\tau \rightarrow 0$.

### Явный метод Эйлера

Проиллюстрируем указанные шаги. Для начала введем расчетную сетку. Очень часто сетка является равномерной, т.е. имеет одинаковое расстояние между узлами $t_{n}$ и $t_{n+1}$:
$$\omega_{\tau} = \left \{ t_{n} = n\tau, n = 0,1,...,N_{t} \right \}.$$

Затем, предполагаем, что уравнение выполнено в узлах сетки, т.е.: 
$$u'(t_{n} = F(t_{n}, u(t_{n}))$$

Заменяем производные конечными разностями. Запишем определение производной в произвольном узле сетки $t_{n}$: 
$$u'(t_{n}) = \lim_{\tau \rightarrow 0} \frac{u(t_{n}+\tau)-u(t_{n})}{\tau}$$

Вместо того, чтобы устремлять шаг сетки к нулю, мы можем использовать малый шаг $\tau$, который даст численное приближение $u'(t_{n})$: 
$$u'(t_{n}) \approx \frac{u^{n+1}-u^{n}}{\tau}$$

Такая аппроксимация известна как разностная производная вперед и имеет первый порядок по $\tau$, то есть $O(\tau)$. Теперь можно использовать аппроксимацию производной. Таким образом получим явный метод Эйлера: 
$$\frac{y^{n+1}-y^{n}}{\tau} = F(t_{n}, y^{n})$$

Выразим $y^{n+1}$: $$y^{n+1} = y^{n} + \tau F(t_{n}, y^{n})$$

При условии, что $y^{0} = u_{0}$, можно находить решения на последующих временных слоях.

### Неявный метод Эйлера

При построении неявного метода Эйлера значение функции ${F}$ берется на новом временном слое, т.е. 
$$\frac{y^{n+1}-y^{n}}{\tau} = F(t_{n+1}, y^{n+1})$$

Таким образом для нахождения приближенного значения искомой функции на новом временном слое $t_{n+1}$ нужно решить нелинейное уравнение относительно $y^{n+1}$: $$y^{n+1} - \tau F(t_{n+1}, y^{n+1}) - y^{n} = 0$$

Для решения уравнения можно использовать метод прогонки или метод Ньютона.

### Усовершенствованный метод Эйлера 2-го порядка

ПРОДОЛЖЕНИЕ СЛЕДУЕТ...

## 2. Реализация методов решения ОДУ

Необходимо решить дифференциальное уравнение

$$\left\{\begin{matrix}
\frac{\mathrm{d} y}{\mathrm{d} t} = 998y + 1998z\\ 
\frac{\mathrm{d} z}{\mathrm{d} t} = -999y - 1999z
\end{matrix}\right.$$
с начальными условиями $y(0)=1, z(0)=1$

Для решения ДУ были использованы методы: явный и неявный методы Эйлера

Реализация данных методов:

In [87]:
import matplotlib.pyplot as plt
import numpy as np
from scipy import optimize
from typing import Callable

In [147]:
def du(t: list, u: list):
    return [998 * u[0] + 1998 * u[1], -999 * u[0] - 1999 * u[1]]
    

def explicity_euler(du: Callable, u0: list, tau: float, T_size: float) -> list and list:
    amount_t = int(round(T_size / tau))
    t = np.linspace(0, amount_t * tau, amount_t + 1)
    u = np.zeros((amount_t + 1, len(u0)))
    u[0] = u0
    for i in range(amount_t):
        du_ = np.asarray(du(t[i], u[i]))
        u[i + 1] = u[i] + tau * du_
    return u, t


def implicity_euler(du: Callable, u0: list, tau: float, T_size: float) -> list and list:
    amount_t = int(round(T_size / tau))
    du_ = lambda t, u: np.asarray(du(t, u))
    t = np.linspace(0, amount_t * tau, amount_t + 1)
    u = np.zeros((amount_t + 1, len(u0)))
    u[0] = u0
    
    def func(a, t, b):
        return a - tau * du_(t, a) - b
    
    for i in range(amount_t):
        u[i + 1] = optimize.fsolve(func, u[i], args=(t[i], u[i]))
    return u, t


T_size = 0.1

## 3. Итоговые результаты

### Явный метод Эйлера 
Шаг $\tau=0.001$:

In [166]:
tau = 0.001
explicity_euler(du, u0 = [1, 1], tau=tau, T_size=T_size)

(array([[ 1.        ,  1.        ],
        [ 3.996     , -1.998     ],
        [ 3.992004  , -1.996002  ],
        [ 3.988012  , -1.994006  ],
        [ 3.98402398, -1.99201199],
        [ 3.98003996, -1.99001998],
        [ 3.97605992, -1.98802996],
        [ 3.97208386, -1.98604193],
        [ 3.96811178, -1.98405589],
        [ 3.96414366, -1.98207183],
        [ 3.96017952, -1.98008976],
        [ 3.95621934, -1.97810967],
        [ 3.95226312, -1.97613156],
        [ 3.94831086, -1.97415543],
        [ 3.94436255, -1.97218127],
        [ 3.94041819, -1.97020909],
        [ 3.93647777, -1.96823888],
        [ 3.93254129, -1.96627064],
        [ 3.92860875, -1.96430437],
        [ 3.92468014, -1.96234007],
        [ 3.92075546, -1.96037773],
        [ 3.9168347 , -1.95841735],
        [ 3.91291787, -1.95645893],
        [ 3.90900495, -1.95450248],
        [ 3.90509595, -1.95254797],
        [ 3.90119085, -1.95059543],
        [ 3.89728966, -1.94864483],
        [ 3.89339237, -1.946

Шаг $\tau=0.002$:

In [167]:
tau = 0.002
explicity_euler(du, u0 = [1, 1], tau=tau, T_size=T_size)

(array([[ 1.        ,  1.        ],
        [ 6.992     , -4.996     ],
        [ 0.984016  ,  1.007992  ],
        [ 6.97604797, -4.98802398],
        [ 0.96809587,  1.01595206],
        [ 6.96015968, -4.98007984],
        [ 0.95223936,  1.02388032],
        [ 6.94433488, -4.97216744],
        [ 0.93644621,  1.03177689],
        [ 6.92857332, -4.96428666],
        [ 0.92071617,  1.03964191],
        [ 6.91287474, -4.95643737],
        [ 0.90504899,  1.0474755 ],
        [ 6.89723889, -4.94861945],
        [ 0.88944442,  1.05527779],
        [ 6.88166553, -4.94083276],
        [ 0.8739022 ,  1.0630489 ],
        [ 6.86615439, -4.9330772 ],
        [ 0.85842208,  1.07078896],
        [ 6.85070524, -4.92535262],
        [ 0.84300383,  1.07849809],
        [ 6.83531782, -4.91765891],
        [ 0.82764718,  1.08617641],
        [ 6.81999189, -4.90999595],
        [ 0.81235191,  1.09382405],
        [ 6.8047272 , -4.9023636 ],
        [ 0.79711775,  1.10144113],
        [ 6.78952351, -4.894

Шаг $\tau=0.0025$:

In [168]:
tau = 0.0025
explicity_euler(du, u0 = [1, 1], tau=tau, T_size=T_size)

(array([[ 1.00000000e+00,  1.00000000e+00],
        [ 8.49000000e+00, -6.49500000e+00],
        [-2.76997500e+00,  4.75998750e+00],
        [ 1.40950749e+01, -1.21100375e+01],
        [-1.12273502e+01,  1.32074251e+01],
        [ 2.67314994e+01, -2.47563747e+01],
        [-3.02315012e+01,  3.22016881e+01],
        [ 5.51883353e+01, -5.32230739e+01],
        [-7.29660222e+01,  7.49263705e+01],
        [ 1.19240973e+02, -1.17285526e+02],
        [-1.69094000e+02,  1.71044558e+02],
        [ 2.63384041e+02, -2.61438358e+02],
        [-3.85357377e+02,  3.87298196e+02],
        [ 5.87730453e+02, -5.85794487e+02],
        [-8.71925528e+02,  8.73856655e+02],
        [ 1.31753427e+03, -1.31560797e+03],
        [-1.96667954e+03,  1.96860102e+03],
        [ 2.95961712e+03, -2.95770044e+03],
        [-4.42985187e+03,  4.43176375e+03],
        [ 6.65432768e+03, -6.65242057e+03],
        [-9.97196551e+03,  9.97386785e+03],
        [ 1.49674505e+04, -1.49655529e+04],
        [-2.24416972e+04,  2.244

### Неявный метод Эйлера 
Шаг $\tau=0.001$:

In [169]:
tau = 0.001
implicity_euler(du, u0 = [1, 1], tau=tau, T_size=T_size)

(array([[ 1.        ,  1.        ],
        [ 2.496004  , -0.498002  ],
        [ 3.24201198, -1.24600599],
        [ 3.61302396, -1.61901198],
        [ 3.79653992, -1.80451996],
        [ 3.88630986, -1.89627993],
        [ 3.92920878, -1.94116689],
        [ 3.94867416, -1.96261833],
        [ 3.95642477, -1.97235301],
        [ 3.95831997, -1.9762303 ],
        [ 3.95728944, -1.97717987],
        [ 3.95479802, -1.97666659],
        [ 3.95157813, -1.97542285],
        [ 3.94799598, -1.97381488],
        [ 3.94423466, -1.97202578],
        [ 3.94038574, -1.97014709],
        [ 3.93649498, -1.9682246 ],
        [ 3.93258526, -1.96628118],
        [ 3.92866802, -1.96432829],
        [ 3.92474899, -1.96237163],
        [ 3.92083101, -1.96041408],
        [ 3.91691553, -1.95845705],
        [ 3.91300324, -1.95650126],
        [ 3.9090945 , -1.95454707],
        [ 3.90518949, -1.95259466],
        [ 3.90128829, -1.9506441 ],
        [ 3.89739095, -1.94869545],
        [ 3.89349747, -1.946

Шаг $\tau=0.002$:

In [170]:
tau = 0.002
implicity_euler(du, u0 = [1, 1], tau=tau, T_size=T_size)

(array([[ 1.        ,  1.        ],
        [ 2.99201597, -0.99600798],
        [ 3.65071454, -1.6586906 ],
        [ 3.86498457, -1.87693673],
        [ 3.93112233, -1.94704264],
        [ 3.94789321, -1.96777376],
        [ 3.94821899, -1.97205188],
        [ 3.94307358, -1.97085092],
        [ 3.93611493, -1.96782884],
        [ 3.92856234, -1.96420496],
        [ 3.9208222 , -1.9603857 ],
        [ 3.91302998, -1.95650652],
        [ 3.90523079, -1.95261257],
        [ 3.89743967, -1.9487189 ],
        [ 3.8896616 , -1.94483049],
        [ 3.88189823, -1.94094901],
        [ 3.87415006, -1.937075  ],
        [ 3.86641728, -1.93320863],
        [ 3.85869989, -1.92934994],
        [ 3.8509979 , -1.92549895],
        [ 3.84331128, -1.92165564],
        [ 3.83564   , -1.91782   ],
        [ 3.82798403, -1.91399202],
        [ 3.82034335, -1.91017167],
        [ 3.81271791, -1.90635896],
        [ 3.8051077 , -1.90255385],
        [ 3.79751267, -1.89875634],
        [ 3.7899328 , -1.894

Шаг $\tau=0.0025$:

In [171]:
tau = 0.0025
implicity_euler(du, u0 = [1, 1], tau=tau, T_size=T_size)

(array([[ 1.        ,  1.        ],
        [ 3.13288208, -1.13786961],
        [ 3.73517679, -1.74513942],
        [ 3.90017853, -1.91510384],
        [ 3.94025709, -1.96013271],
        [ 3.94466092, -1.96947451],
        [ 3.93888955, -1.96862879],
        [ 3.9302285 , -1.96488111],
        [ 3.92075933, -1.96031305],
        [ 3.9110767 , -1.95551932],
        [ 3.90135049, -1.95066981],
        [ 3.89162917, -1.94581303],
        [ 3.88192657, -1.94096284],
        [ 3.87224659, -1.93612317],
        [ 3.8625903 , -1.93129511],
        [ 3.85295795, -1.92647897],
        [ 3.84334959, -1.92167479],
        [ 3.83376518, -1.91688259],
        [ 3.82420467, -1.91210234],
        [ 3.814668  , -1.907334  ],
        [ 3.80515512, -1.90257756],
        [ 3.79566595, -1.89783298],
        [ 3.78620045, -1.89310023],
        [ 3.77675855, -1.88837928],
        [ 3.7673402 , -1.8836701 ],
        [ 3.75794534, -1.87897267],
        [ 3.74857391, -1.87428695],
        [ 3.73922584, -1.869